name: Dry run release

on:
  pull_request:

jobs:
  dry-run-release:
    name: dry-run-release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js, pnpm and Nx cache
        uses: ./.github/actions/setup

      - name: Dry run release
        run: pnpm relizy release --dry-run
